### ISSUE TITLE
Data not being displayed.

### ISSUE THREAD

**Issue by rolandblais** [thesoftwarejedi/MMM-YNAB#1]
Data doesn't show up using MagicMirror v2.15.0 (fresh install). Clock Module and MMM-YNAB are the only modules registered. log seems to indicate API is working. I defined 1 category; it's in the "list" output, but the Mirror Display does not show anything other than the Clock module. I've tried changing the position attribute to no effect.

**Comment by thesoftwarejedi** [comment]
I just added some logging to the client js file - if you could update to the latest and share the output of both the server AND the web browser console, that'd be great.

**Comment by rolandblais** [comment]
Hi. Thanks for taking a look at this so quickly.

This is what I get at startup now:

> magicmirror@2.15.0 start
> DISPLAY="${DISPLAY:=:0}" ./node_modules/.bin/electron js/electron.js

[23.04.2021 08:46.59.519] [LOG]   Starting MagicMirror: v2.15.0
[23.04.2021 08:46.59.521] [LOG]   Loading config ...
[23.04.2021 08:46.59.523] [LOG]   Loading module helpers ...
[23.04.2021 08:46.59.523] [LOG]   No helper found for module: alert.
[23.04.2021 08:46.59.574] [LOG]   Initializing new module helper ...
[23.04.2021 08:46.59.575] [LOG]   Module helper loaded: updatenotification
[23.04.2021 08:46.59.575] [LOG]   No helper found for module: clock.
[23.04.2021 08:46.59.578] [LOG]   Loading module helpers ...
[23.04.2021 08:46.59.579] [LOG]   No helper found for module: alert.
[23.04.2021 08:46.59.579] [LOG]   Initializing new module helper ...
[23.04.2021 08:46.59.579] [LOG]   Module helper loaded: updatenotification
[23.04.2021 08:46.59.579] [LOG]   No helper found for module: clock.
[23.04.2021 08:46.59.718] [LOG]   Launching application.
[23.04.2021 08:47.11.487] [LOG]   Shutting down server...
rolando@rolando-mm:~/MagicMirror$ npm start >> test.txt
[23.04.2021 08:47.37.928] [ERROR] WARNING! Could not load config file. Starting with default configuration. Error found: Error: Cannot find module '/home/rolando/MagicMirror/modules/MMM-YNAB/node_modules/ynab/index.js'. Please verify that the package.json has a valid "main" entry
[23.04.2021 08:47.37.932] [ERROR] App threw an error during load
[23.04.2021 08:47.37.933] [ERROR] Error: Cannot find module '/home/rolando/MagicMirror/modules/MMM-YNAB/node_modules/ynab/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:328:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:689:18)
    at Module._resolveFilename (internal/modules/cjs/loader.js:959:27)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:249:921)
    at Function.Module._resolveFilename (/home/rolando/MagicMirror/node_modules/module-alias/index.js:49:29)
    at Module._load (internal/modules/cjs/loader.js:848:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/rolando/MagicMirror/modules/MMM-YNAB/node_helper.js:1:14)
[23.04.2021 08:47.37.933] [ERROR] Whoops! There was an uncaught exception...
[23.04.2021 08:47.37.935] [ERROR] Error: Cannot find module '/home/rolando/MagicMirror/modules/MMM-YNAB/node_modules/ynab/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:328:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:689:18)
    at Module._resolveFilename (internal/modules/cjs/loader.js:959:27)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:249:921)
    at Function.Module._resolveFilename (/home/rolando/MagicMirror/node_modules/module-alias/index.js:49:29)
    at Module._load (internal/modules/cjs/loader.js:848:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/rolando/MagicMirror/modules/MMM-YNAB/node_helper.js:1:14) {
  code: 'MODULE_NOT_FOUND',
  path: '/home/rolando/MagicMirror/modules/MMM-YNAB/node_modules/ynab/package.json',
  requestPath: 'ynab'
}
[23.04.2021 08:47.37.936] [ERROR] MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
[23.04.2021 08:47.37.936] [ERROR] If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues

**Comment by thesoftwarejedi** [comment]
That looks like you didn’t run “NPM install” in the folder first.

**Comment by rolandblais** [comment]
Hi. Thanks again for such a quick response. I did run npm install         though. Here, I'll start from scratch:

rolando@rolando-mm:~/MagicMirror/modules$ git clone https://github.com/thesoftwarejedi/MMM-YNAB.git
Cloning into 'MMM-YNAB'...
remote: Enumerating objects: 33, done.
remote: Counting objects: 100% (33/33), done.
remote: Compressing objects: 100% (24/24), done.
remote: Total 33 (delta 16), reused 19 (delta 8), pack-reused 0
Unpacking objects: 100% (33/33), 18.45 KiB | 1.84 MiB/s, done.
rolando@rolando-mm:~/MagicMirror/modules$ cd MMM-YNAB/
rolando@rolando-mm:~/MagicMirror/modules/MMM-YNAB$ npm install

added 8 packages, and audited 9 packages in 975ms

3 low severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
rolando@rolando-mm:~/MagicMirror/modules/MMM-YNAB$ npm audit fix --force
npm WARN using --force Recommended protections disabled.
npm WARN audit Updating ynab to 0.0.1,which is a SemVer major change.

removed 7 packages, changed 1 package, and audited 2 packages in 893ms

found 0 vulnerabilities
rolando@rolando-mm:~/MagicMirror$ npm start

> magicmirror@2.15.0 start
> DISPLAY="${DISPLAY:=:0}" ./node_modules/.bin/electron js/electron.js

[23.04.2021 14:21.04.971] [LOG]   Starting MagicMirror: v2.15.0
[23.04.2021 14:21.04.972] [LOG]   Loading config ...
[23.04.2021 14:21.04.974] [LOG]   Loading module helpers ...
[23.04.2021 14:21.04.975] [LOG]   No helper found for module: alert.
[23.04.2021 14:21.05.032] [LOG]   Initializing new module helper ...
[23.04.2021 14:21.05.032] [LOG]   Module helper loaded: updatenotification
[23.04.2021 14:21.05.032] [LOG]   No helper found for module: clock.
[23.04.2021 14:21.05.035] [ERROR] WARNING! Could not load config file. Starting with default configuration. Error found: Error: Cannot find module '/home/rolando/MagicMirror/modules/MMM-YNAB/node_modules/ynab/index.js'. Please verify that the package.json has a valid "main" entry
[23.04.2021 14:21.05.035] [LOG]   Loading module helpers ...
[23.04.2021 14:21.05.036] [LOG]   No helper found for module: alert.
[23.04.2021 14:21.05.036] [LOG]   Initializing new module helper ...
[23.04.2021 14:21.05.036] [LOG]   Module helper loaded: updatenotification
[23.04.2021 14:21.05.036] [LOG]   No helper found for module: clock.
[23.04.2021 14:21.05.037] [ERROR] App threw an error during load
[23.04.2021 14:21.05.038] [ERROR] Error: Cannot find module '/home/rolando/MagicMirror/modules/MMM-YNAB/node_modules/ynab/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:328:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:689:18)
    at Module._resolveFilename (internal/modules/cjs/loader.js:959:27)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:249:921)
    at Function.Module._resolveFilename (/home/rolando/MagicMirror/node_modules/module-alias/index.js:49:29)
    at Module._load (internal/modules/cjs/loader.js:848:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/rolando/MagicMirror/modules/MMM-YNAB/node_helper.js:1:14)
[23.04.2021 14:21.05.038] [ERROR] Whoops! There was an uncaught exception...
[23.04.2021 14:21.05.040] [ERROR] Error: Cannot find module '/home/rolando/MagicMirror/modules/MMM-YNAB/node_modules/ynab/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:328:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:689:18)
    at Module._resolveFilename (internal/modules/cjs/loader.js:959:27)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:249:921)
    at Function.Module._resolveFilename (/home/rolando/MagicMirror/node_modules/module-alias/index.js:49:29)
    at Module._load (internal/modules/cjs/loader.js:848:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/rolando/MagicMirror/modules/MMM-YNAB/node_helper.js:1:14) {
  code: 'MODULE_NOT_FOUND',
  path: '/home/rolando/MagicMirror/modules/MMM-YNAB/node_modules/ynab/package.json',
  requestPath: 'ynab'
}
[23.04.2021 14:21.05.041] [ERROR] MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
[23.04.2021 14:21.05.041] [ERROR] If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
[23.04.2021 14:21.05.183] [LOG]   Launching application.
^C/home/rolando/MagicMirror/node_modules/electron/dist/electron exited with signal SIGINT

**Comment by thesoftwarejedi** [comment]
When you run `npm audit` it is deleting the YNAB api. Not sure why - but that’s what the log shows. Try without that.

**Comment by devinhedge** [comment]
Probably because the API isn't specifying the budget. E.g. The API request assumes only one budget exists, and doesn't send a payload that contains the budget ID and Budget Name?

See what returns when you run:
`$  curl -H "Authorization: Bearer <ACCESS_TOKEN>" https://api.youneedabudget.com/v1/budgets `

**Comment by thesoftwarejedi** [comment]
> Probably because the API isn't specifying the budget. E.g. The API request assumes only one budget exists, and doesn't send a payload that contains the budget ID and Budget Name?
> 
> See what returns when you run:
> `$ curl -H "Authorization: Bearer <ACCESS_TOKEN>" https://api.youneedabudget.com/v1/budgets`

Ah good catch. The code is automatically grabbing the first budget. 

https://github.com/thesoftwarejedi/MMM-YNAB/blob/c51804a34816a6d8b48af92653a39f04c6e5f112/node_helper.js#L26

You could change the index there if it’s not first. 

I don’t think that’s related to this issue tho

**Comment by rolandblais** [comment]
"Module not found" issue fixed, thank you. Without running "npm audix fix --force" the module worked. 

It now displays "UNDEFINED" in the mirror.

This is the output from "curl -H "Authorization: Bearer <ACCESS_TOKEN>" https://api.youneedabudget.com/v1/budgets":

{"data":{"budgets":[{"id":"e86d68e5-8313-474e-a045-6201a1fbf606","name":"2021 Budget","last_modified_on":"2021-04-26T12:17:29+00:00","first_month":"2020-01-01","last_month":"2021-04-01","date_format":{"format":"MM/DD/YYYY"},"currency_format":{"iso_code":"USD","example_format":"123,456.78","decimal_digits":2,"decimal_separator":".","symbol_first":true,"group_separator":",","currency_symbol":"$","display_symbol":true}}],"default_budget":null}}rolando@rolando-mm:~$

I only have 1 budget, it was identified correctly by name in the curl output.

This is startup now:

26.04.2021 08:51.14.966] [LOG]   Connecting socket for: MMM-YNAB
[26.04.2021 08:51.14.966] [LOG]   Starting module helper: MMM-YNAB
[26.04.2021 08:51.14.967] [LOG]   Sockets connected & modules started ...
[26.04.2021 08:51.15.117] [LOG]   Launching application.
[26.04.2021 08:51.15.699] [LOG]   Notification received: SET_CONFIG
[26.04.2021 08:51.15.699] [LOG]   initialize
[26.04.2021 08:51.15.700] [LOG]   created api
[26.04.2021 08:51.16.247] [LOG]   budgetsResponse: {"data":{"budgets":[{"id":"e86d68e5-8313-474e-a045-6201a1fbf606","name":"2021 Budget","last_modified_on":"2021-04-26T12:17:29+00:00","first_month":"2020-01-01","last_month":"2021-04-01","date_format":{"format":"MM/DD/YYYY"},"currency_format":{"iso_code":"USD","example_format":"123,456.78","decimal_digits":2,"decimal_separator":".","symbol_first":true,"group_separator":",","currency_symbol":"$","display_symbol":true}}],"default_budget":null}}
[26.04.2021 08:51.16.247] [LOG]   updateBudget: e86d68e5-8313-474e-a045-6201a1fbf606
[26.04.2021 08:51.16.247] [LOG]   created api
[26.04.2021 08:51.16.711] [LOG]   got cats
[26.04.2021 08:51.16.712] [LOG]   list: [{"id":"3b192814-d887-4b67-9dc0-2821ddc68c70","category_group_id":"86029517-c7c1-473f-af8f-bd556e2d732d","name":"IRS","hidden":false,"original_category_group_id":null,"note":null,"budgeted":-182770,"activity":0,"balance":1017230,"goal_type":"NEED","goal_creation_month":"2021-03-01","goal_target":1200000,"goal_target_month":"2021-04-01","goal_percentage_complete":84,"goal_months_to_budget":1,"goal_under_funded":182770,"goal_overall_funded":1017230,"goal_overall_left":182770,"deleted":false}]
[26.04.2021 08:51.16.713] [LOG]   sent update
[26.04.2021 08:52.46.266] [LOG]   updateBudget: e86d68e5-8313-474e-a045-6201a1fbf606
[26.04.2021 08:52.46.266] [LOG]   created api
[26.04.2021 08:52.46.775] [LOG]   got cats

Changing the name of my budget to "default_budget" did not change any behavior; the display still reads "UNDEFINED". 

Here's the output from the web console:

TypeError: this.data.items is undefined
    getDom http://127.0.0.1:8080/modules/MMM-YNAB/MMM-YNAB.js:14
    updateDom http://127.0.0.1:8080/js/main.js:114
    updateDom http://127.0.0.1:8080/js/main.js:113
    createDomObjects http://127.0.0.1:8080/js/main.js:53
    createDomObjects http://127.0.0.1:8080/js/main.js:20
    modulesStarted http://127.0.0.1:8080/js/main.js:510
    startModules http://127.0.0.1:8080/js/loader.js:56
    loadNextModule http://127.0.0.1:8080/js/loader.js:38
    onerror http://127.0.0.1:8080/js/loader.js:217

Uncaught (in promise) TypeError: this.data.items is undefined
    getDom http://127.0.0.1:8080/modules/MMM-YNAB/MMM-YNAB.js:14
    updateDom http://127.0.0.1:8080/js/main.js:114
    updateDom http://127.0.0.1:8080/js/main.js:113
    createDomObjects http://127.0.0.1:8080/js/main.js:53
    createDomObjects http://127.0.0.1:8080/js/main.js:20
    modulesStarted http://127.0.0.1:8080/js/main.js:510
    startModules http://127.0.0.1:8080/js/loader.js:56
    loadNextModule http://127.0.0.1:8080/js/loader.js:38
    onerror http://127.0.0.1:8080/js/loader.js:217

Thanks again for your time.

**Comment by Raab70** [comment]
I was seeing similar issues with data not being displayed. First I found that this line https://github.com/thesoftwarejedi/MMM-YNAB/blob/c51804a34816a6d8b48af92653a39f04c6e5f112/MMM-YNAB.js#L14 is failing because `this.data` is undefined. I was able to get past that by replacing it with: 
```javascript
        if (this.data.items) {
            console.log('Data length: ' + this.data.items.length);
        } else {
            console.log('No Items!')
        }
```

That is the last part of the previous comment: `TypeError: this.data.items is undefined`

After fixing that though, I was still not seeing my data rendered. I was instead getting: 
```
module tries to update the DOM without being displayed.
updateDom @ main.js:553
updateDom @ module.js:364
socketNotificationReceived @ MMM-YNAB.js:32
(anonymous) @ module.js:250
(anonymous) @ socketclient.js:39
./node_modules/component-emitter/index.js.Emitter.emit @ index.js:145
emit @ typed-events.js:46
emitEvent @ socket.js:263
onevent @ socket.js:250
MMSocket.self.socket.onevent @ socketclient.js:33
onpacket @ socket.js:214
./node_modules/component-emitter/index.js.Emitter.emit @ index.js:145
emitReserved @ typed-events.js:59
ondecoded @ manager.js:207
./node_modules/component-emitter/index.js.Emitter.emit @ index.js:145
add @ index.js:117
ondata @ manager.js:199
./node_modules/component-emitter/index.js.Emitter.emit @ index.js:145
onPacket @ socket.js:407
(anonymous) @ socket.js:216
./node_modules/component-emitter/index.js.Emitter.emit @ index.js:145
onPacket @ transport.js:103
onData @ transport.js:96
ws.onmessage @ websocket.js:111
```

Which looks to be coming from this line: https://github.com/thesoftwarejedi/MMM-YNAB/blob/c51804a34816a6d8b48af92653a39f04c6e5f112/MMM-YNAB.js#L28

This looks to be a collision, probably something new with 2.15.0 that they're using `this.data` for some internals. I can see that the issue coming from updateDom is because `module.data.position` does not exist and this is because it's being overwritten by the YNAB data. I changed all references in `MMM-YNAB.js` to `this.data` to instead use `this.result` and the module worked. I'd be happy to submit a patch if you'd like.

**Comment by thesoftwarejedi** [comment]
Sounds great - yeah shoot a PR if you could and I'll get it merged in!  Thanks!

**Comment by rolandblais** [comment]
Thank you for working on this! I was able to hand edit MMM-YNAB.js and node_helper.js and it worked.

One last request or perhaps just point me in the right direction - is there a way to display the results as a vertical list, rather than horizontal?

Thanks again!

**Comment by thesoftwarejedi** [comment]
> Thank you for working on this! I was able to hand edit MMM-YNAB.js and node_helper.js and it worked.
> 
> One last request or perhaps just point me in the right direction - is there a way to display the results as a vertical list, rather than horizontal?
> 
> Thanks again!

@rolandblais Open an issue for the "vertical display" option.  Someone might pick it up and work on it.  I'm too busy right now and have little experience in MMM stuff.
